### ISSUE TITLE
Confused as hell

### ISSUE THREAD

**Issue by Badxpatrick** [JackNoordhuis/DiscordPHP#1]
Sorry, but the instructions are confusing as hell. Could you please make a video showing how exactly to set this up?

Will this work on Windows?

Can I use this to bridge my in-game server chat, such as Unturned, to a discord text channel?

**Comment by JackNoordhuis** [comment]
This is a continuation of https://github.com/teamreflex/DiscordPHP, the master branch is just a clone. The old implementation will need to be modified if you wish to use it within a plugin.

**Comment by Badxpatrick** [comment]
Vague as hell again. Well, thanks anyways.

**Comment by JackNoordhuis** [comment]
Read what I said -- I did not write the library.

I've never used the library and it currently only supports CLI applications which makes it difficult to use in a plugin, hence why I decided to 'start' rewriting it.
